### ISSUE TITLE
ImportError: No module named _md5

### ISSUE THREAD

**Issue by LeslieZhu** [LeslieZhu/MinYi#42]
Got a error on test env with python2.7.9: 

```
 $ pip
Traceback (most recent call last):
  File "/UBSys/local/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/local/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 11, in <module>
    from pip.download import path_to_url
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 5, in <module>
    import hashlib
  File "/usr/local/lib/python2.7/hashlib.py", line 136, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 71, in __get_builtin_constructor
    import _md5
ImportError: No module named _md5
```

**Comment by LeslieZhu** [comment]
maybe openssl package not work, try:

```
yum -y install   openssl openssl-devel
```
